### ISSUE TITLE
Command - initial user stories 

### ISSUE THREAD

**Issue by 123aswin123** [123aswin123/timebomb#11]
# This issue has been opened to write the initial user stories for the Vedi project. 💻 

`vedi new ec2` - creates a new t2.micro instance that auto-destroys in 30 minutes, t2.micro and 30 minutes are defaults.

`vedi new ec2 --time=10hours` - creates a new EC2 t2.micro instance that would auto destroy in 10 hours.

`vedi new ec2 -t=20minutes` - supports shorthand flags like -t for time.

`vedi new ec2 -t=10` -  when no time unit is specified with time, it defaults to minutes (10 mins in this case).

`vedi new ec2 --instance=t2.nano` - support for the instance flag.

`vedi new ec2 --instance=t2nano` - support for fuzzy string matching in instance names.

`vedi new ec2 --sku=1337` - support for the instance's SKU flag.

`vedi new ec2 --ami=a-123` - support for launch with AMI ID.

`vedi new ec2 --count=5` - launches 5 t2.micro instances.

`vedi new ec2 --ami=a-321 --count=2 --ami=a-456 --count=3` - @shivasurya @Laksh47, better alternatives to do this?

`vedi new ec2 -t=12months` - 12 months is the maximum for supported time-period, @shivasurya @Laksh47 thoughts?

`vedi new ec2 --spot` - A boolean flag for spot instances

`vedi new ec2 --region=useast2` - A flag to specify region.

**Comment by shivasurya** [comment]
LGTM bro 🚀🚀🚀

**Comment by Laksh47** [comment]
@shivasurya @123aswin123 Should we not have the time (the number) and the unit (minutes) as diff args? or at least have them seperated by a space "12 minutes"

**Comment by Laksh47** [comment]
I am okay with 12 months and single instance with count option! "make it work first and make it better" @123aswin123

**Comment by Laksh47** [comment]
What is --ami? @shivasurya @123aswin123

**Comment by s5dev** [comment]
@Laksh47  AMI Definition ( https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html )- just OS copy/instance snapshot. just like a docker image.

**Comment by 123aswin123** [comment]
> @shivasurya @123aswin123 Should we not have the time (the number) and the unit (minutes) as diff args? or at least have them seperated by a space "12 minutes"

We are going to use https://www.npmjs.com/package/timestring and this will convert human readable timestrings to seconds.

**Comment by 123aswin123** [comment]
Houston, we have a problem, "new" is a reserved word in JS, however there  are workarounds  to use the 'new' keyword,

However we can also switch to spawn or create. eg: `timebomb spawn ec2 ` or `timebomb create ec2` vs `timebomb new ec2`.

Should we stick to new or should we switch, do you foresee any big problems?

**Comment by Laksh47** [comment]
@123aswin123 @shivasurya I think we it doesn't hurt to switch. Personally, I like spawn/create than new! :P

We don't want to stumble into reserved keyword problems and work around it always!
