### ISSUE TITLE
Try to identify dependencies and dev dependencies

### ISSUE THREAD

**Issue by 123aswin123** [123aswin123/timebomb#2]
Add dependence to package.json

**Comment by shivasurya** [comment]
1. Momentjs for parsing time ( moment )
2. AWS JS SDK - [Exact Termination API](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EC2.html#terminateInstances-property) 
3. Use child_process to execute cron for linux OS

@Laksh47  @123aswin123

**Comment by shivasurya** [comment]
`var params = {
  InstanceIds: [
     "i-1234567890abcdef0"
  ]
 };
 ec2.terminateInstances(params, function(err, data) {
   if (err) console.log(err, err.stack); // an error occurred
   else     console.log(data);           // successful response
   /*
   data = {
    TerminatingInstances: [
       {
      CurrentState: {
       Code: 32, 
       Name: "shutting-down"
      }, 
      InstanceId: "i-1234567890abcdef0", 
      PreviousState: {
       Code: 16, 
       Name: "running"
      }
     }
    ]
   }
   */
 });`

**Comment by 123aswin123** [comment]
https://momentjs.com/docs/#/-project-status/ @shivasurya moment itself is recommending other options!

**Comment by 123aswin123** [comment]
@shivasurya 

I think this is what we are looking for
