### ISSUE TITLE
Figure out how to access AWS credentials.

### ISSUE THREAD

**Issue by 123aswin123** [123aswin123/timebomb#25]
We need to decide on the way(s) in which we are going to check the presence of AWS keys.

**Comment by 123aswin123** [comment]
@shivasurya @Laksh47 Any thoughts as to how we're going to access the AWS credentials?

1) A few options that come to mind, look for it in the environment or prompt.
2) error out if no aws credentials are provided.

**Comment by Laksh47** [comment]
file path as an arg should be fine right? @123aswin123
